[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock_usdc_token = "3XDGbzBFhxCvwg89j6ZQ6B2KHgRXDmEFtZvf8x2cxnq2"

[programs.devnet]
mock_usdc_token = "3XDGbzBFhxCvwg89j6ZQ6B2KHgRXDmEFtZvf8x2cxnq2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
